# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/LEDcounter_scutimer_interrupt/LEDcounter_scutimer_interrupt.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LEDcounter_scutimer_interrupt || ORIG_REF_NAME==LEDcounter_scutimer_interrupt}]

# IP: bd/LEDcounter_scutimer_interrupt/ip/LEDcounter_scutimer_interrupt_processing_system7_0_0/LEDcounter_scutimer_interrupt_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LEDcounter_scutimer_interrupt_processing_system7_0_0 || ORIG_REF_NAME==LEDcounter_scutimer_interrupt_processing_system7_0_0}]

# IP: bd/LEDcounter_scutimer_interrupt/ip/LEDcounter_scutimer_interrupt_axi_gpio_0_0/LEDcounter_scutimer_interrupt_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LEDcounter_scutimer_interrupt_axi_gpio_0_0 || ORIG_REF_NAME==LEDcounter_scutimer_interrupt_axi_gpio_0_0}]

# IP: bd/LEDcounter_scutimer_interrupt/ip/LEDcounter_scutimer_interrupt_processing_system7_0_axi_periph_0/LEDcounter_scutimer_interrupt_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LEDcounter_scutimer_interrupt_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==LEDcounter_scutimer_interrupt_processing_system7_0_axi_periph_0}]

# IP: bd/LEDcounter_scutimer_interrupt/ip/LEDcounter_scutimer_interrupt_rst_processing_system7_0_100M_0/LEDcounter_scutimer_interrupt_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LEDcounter_scutimer_interrupt_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==LEDcounter_scutimer_interrupt_rst_processing_system7_0_100M_0}]

# IP: bd/LEDcounter_scutimer_interrupt/ip/LEDcounter_scutimer_interrupt_auto_pc_0/LEDcounter_scutimer_interrupt_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LEDcounter_scutimer_interrupt_auto_pc_0 || ORIG_REF_NAME==LEDcounter_scutimer_interrupt_auto_pc_0}]

# XDC: bd/LEDcounter_scutimer_interrupt/ip/LEDcounter_scutimer_interrupt_processing_system7_0_0/LEDcounter_scutimer_interrupt_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==LEDcounter_scutimer_interrupt_processing_system7_0_0 || ORIG_REF_NAME==LEDcounter_scutimer_interrupt_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/LEDcounter_scutimer_interrupt/ip/LEDcounter_scutimer_interrupt_axi_gpio_0_0/LEDcounter_scutimer_interrupt_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==LEDcounter_scutimer_interrupt_axi_gpio_0_0 || ORIG_REF_NAME==LEDcounter_scutimer_interrupt_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/LEDcounter_scutimer_interrupt/ip/LEDcounter_scutimer_interrupt_axi_gpio_0_0/LEDcounter_scutimer_interrupt_axi_gpio_0_0_ooc.xdc

# XDC: bd/LEDcounter_scutimer_interrupt/ip/LEDcounter_scutimer_interrupt_axi_gpio_0_0/LEDcounter_scutimer_interrupt_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==LEDcounter_scutimer_interrupt_axi_gpio_0_0 || ORIG_REF_NAME==LEDcounter_scutimer_interrupt_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/LEDcounter_scutimer_interrupt/ip/LEDcounter_scutimer_interrupt_rst_processing_system7_0_100M_0/LEDcounter_scutimer_interrupt_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==LEDcounter_scutimer_interrupt_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==LEDcounter_scutimer_interrupt_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/LEDcounter_scutimer_interrupt/ip/LEDcounter_scutimer_interrupt_rst_processing_system7_0_100M_0/LEDcounter_scutimer_interrupt_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==LEDcounter_scutimer_interrupt_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==LEDcounter_scutimer_interrupt_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/LEDcounter_scutimer_interrupt/ip/LEDcounter_scutimer_interrupt_rst_processing_system7_0_100M_0/LEDcounter_scutimer_interrupt_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/LEDcounter_scutimer_interrupt/ip/LEDcounter_scutimer_interrupt_auto_pc_0/LEDcounter_scutimer_interrupt_auto_pc_0_ooc.xdc

# XDC: bd/LEDcounter_scutimer_interrupt/LEDcounter_scutimer_interrupt_ooc.xdc
