# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/interrupt_counter/interrupt_counter.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_counter || ORIG_REF_NAME==interrupt_counter} -quiet] -quiet

# IP: bd/interrupt_counter/ip/interrupt_counter_processing_system7_0_0/interrupt_counter_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_counter_processing_system7_0_0 || ORIG_REF_NAME==interrupt_counter_processing_system7_0_0} -quiet] -quiet

# IP: bd/interrupt_counter/ip/interrupt_counter_axi_gpio_0_0/interrupt_counter_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_counter_axi_gpio_0_0 || ORIG_REF_NAME==interrupt_counter_axi_gpio_0_0} -quiet] -quiet

# IP: bd/interrupt_counter/ip/interrupt_counter_axi_gpio_1_0/interrupt_counter_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_counter_axi_gpio_1_0 || ORIG_REF_NAME==interrupt_counter_axi_gpio_1_0} -quiet] -quiet

# IP: bd/interrupt_counter/ip/interrupt_counter_xbar_0/interrupt_counter_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_counter_xbar_0 || ORIG_REF_NAME==interrupt_counter_xbar_0} -quiet] -quiet

# IP: bd/interrupt_counter/ip/interrupt_counter_ps7_0_axi_periph_0/interrupt_counter_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_counter_ps7_0_axi_periph_0 || ORIG_REF_NAME==interrupt_counter_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/interrupt_counter/ip/interrupt_counter_rst_ps7_0_100M_0/interrupt_counter_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_counter_rst_ps7_0_100M_0 || ORIG_REF_NAME==interrupt_counter_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/interrupt_counter/ip/interrupt_counter_auto_pc_0/interrupt_counter_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_counter_auto_pc_0 || ORIG_REF_NAME==interrupt_counter_auto_pc_0} -quiet] -quiet

# IP: bd/interrupt_counter/ip/interrupt_counter_axi_timer_0_0/interrupt_counter_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_counter_axi_timer_0_0 || ORIG_REF_NAME==interrupt_counter_axi_timer_0_0} -quiet] -quiet

# IP: bd/interrupt_counter/ip/interrupt_counter_xlconcat_0_0/interrupt_counter_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_counter_xlconcat_0_0 || ORIG_REF_NAME==interrupt_counter_xlconcat_0_0} -quiet] -quiet

# XDC: bd/interrupt_counter/ip/interrupt_counter_processing_system7_0_0/interrupt_counter_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==interrupt_counter_processing_system7_0_0 || ORIG_REF_NAME==interrupt_counter_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/interrupt_counter/ip/interrupt_counter_axi_gpio_0_0/interrupt_counter_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==interrupt_counter_axi_gpio_0_0 || ORIG_REF_NAME==interrupt_counter_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/interrupt_counter/ip/interrupt_counter_axi_gpio_0_0/interrupt_counter_axi_gpio_0_0_ooc.xdc

# XDC: bd/interrupt_counter/ip/interrupt_counter_axi_gpio_0_0/interrupt_counter_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==interrupt_counter_axi_gpio_0_0 || ORIG_REF_NAME==interrupt_counter_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/interrupt_counter/ip/interrupt_counter_axi_gpio_1_0/interrupt_counter_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==interrupt_counter_axi_gpio_1_0 || ORIG_REF_NAME==interrupt_counter_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/interrupt_counter/ip/interrupt_counter_axi_gpio_1_0/interrupt_counter_axi_gpio_1_0_ooc.xdc

# XDC: bd/interrupt_counter/ip/interrupt_counter_axi_gpio_1_0/interrupt_counter_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==interrupt_counter_axi_gpio_1_0 || ORIG_REF_NAME==interrupt_counter_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/interrupt_counter/ip/interrupt_counter_rst_ps7_0_100M_0/interrupt_counter_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==interrupt_counter_rst_ps7_0_100M_0 || ORIG_REF_NAME==interrupt_counter_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/interrupt_counter/ip/interrupt_counter_rst_ps7_0_100M_0/interrupt_counter_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==interrupt_counter_rst_ps7_0_100M_0 || ORIG_REF_NAME==interrupt_counter_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/interrupt_counter/ip/interrupt_counter_auto_pc_0/interrupt_counter_auto_pc_0_ooc.xdc

# XDC: bd/interrupt_counter/ip/interrupt_counter_axi_timer_0_0/interrupt_counter_axi_timer_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==interrupt_counter_axi_timer_0_0 || ORIG_REF_NAME==interrupt_counter_axi_timer_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/interrupt_counter/ip/interrupt_counter_axi_timer_0_0/interrupt_counter_axi_timer_0_0_ooc.xdc

# XDC: bd/interrupt_counter/interrupt_counter_ooc.xdc
