#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Jan 14 03:16:11 EST 2022
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto dda8ef574e2c4de080d6caf4689b4fc6 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot BaudRateGeneratorTB_behav xil_defaultlib.BaudRateGeneratorTB xil_defaultlib.glbl -log elaborate.log"
xelab -wto dda8ef574e2c4de080d6caf4689b4fc6 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot BaudRateGeneratorTB_behav xil_defaultlib.BaudRateGeneratorTB xil_defaultlib.glbl -log elaborate.log

