# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-283564-skilletLaptop/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/skillet/git/ECE530/Lab10/lab10VGAblockdesignonlyJJS/lab10VGAdemoJJS/lab10VGAdemoJJS.cache/wt [current_project]
set_property parent.project_path /home/skillet/git/ECE530/Lab10/lab10VGAblockdesignonlyJJS/lab10VGAdemoJJS/lab10VGAdemoJJS.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths /home/skillet/git/ECE530/Lab10/lab10VGAblockdesignonlyJJS/lab10VGAdemoJJS/zybo_base_system_lib [current_project]
update_ip_catalog
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib /home/skillet/git/ECE530/Lab10/lab10VGAblockdesignonlyJJS/lab10VGAdemoJJS/lab10VGAdemoJJS.srcs/sources_1/bd/lab9VGA/hdl/lab9VGA_wrapper.v
add_files /home/skillet/git/ECE530/Lab10/lab10VGAblockdesignonlyJJS/lab10VGAdemoJJS/lab10VGAdemoJJS.srcs/sources_1/bd/lab9VGA/lab9VGA.bd
set_property used_in_implementation false [get_files -all /home/skillet/git/ECE530/Lab10/lab10VGAblockdesignonlyJJS/lab10VGAdemoJJS/lab10VGAdemoJJS.srcs/sources_1/bd/lab9VGA/ip/lab9VGA_processing_system7_0_1/lab9VGA_processing_system7_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/skillet/git/ECE530/Lab10/lab10VGAblockdesignonlyJJS/lab10VGAdemoJJS/lab10VGAdemoJJS.srcs/sources_1/bd/lab9VGA/ip/lab9VGA_axi_vdma_0_1/lab9VGA_axi_vdma_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/skillet/git/ECE530/Lab10/lab10VGAblockdesignonlyJJS/lab10VGAdemoJJS/lab10VGAdemoJJS.srcs/sources_1/bd/lab9VGA/ip/lab9VGA_axi_vdma_0_1/lab9VGA_axi_vdma_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/skillet/git/ECE530/Lab10/lab10VGAblockdesignonlyJJS/lab10VGAdemoJJS/lab10VGAdemoJJS.srcs/sources_1/bd/lab9VGA/ip/lab9VGA_axi_vdma_0_1/lab9VGA_axi_vdma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skillet/git/ECE530/Lab10/lab10VGAblockdesignonlyJJS/lab10VGAdemoJJS/lab10VGAdemoJJS.srcs/sources_1/bd/lab9VGA/ip/lab9VGA_xbar_2/lab9VGA_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skillet/git/ECE530/Lab10/lab10VGAblockdesignonlyJJS/lab10VGAdemoJJS/lab10VGAdemoJJS.srcs/sources_1/bd/lab9VGA/ip/lab9VGA_xbar_3/lab9VGA_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skillet/git/ECE530/Lab10/lab10VGAblockdesignonlyJJS/lab10VGAdemoJJS/lab10VGAdemoJJS.srcs/sources_1/bd/lab9VGA/ip/lab9VGA_auto_pc_0/lab9VGA_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skillet/git/ECE530/Lab10/lab10VGAblockdesignonlyJJS/lab10VGAdemoJJS/lab10VGAdemoJJS.srcs/sources_1/bd/lab9VGA/ip/lab9VGA_auto_pc_1/lab9VGA_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skillet/git/ECE530/Lab10/lab10VGAblockdesignonlyJJS/lab10VGAdemoJJS/lab10VGAdemoJJS.srcs/sources_1/bd/lab9VGA/lab9VGA_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/skillet/git/ECE530/Lab10/lab10VGAblockdesignonlyJJS/lab10VGAdemoJJS/lab10VGAdemoJJS.srcs/constrs_1/new/lab9VGA_wrapper.xdc
set_property used_in_implementation false [get_files /home/skillet/git/ECE530/Lab10/lab10VGAblockdesignonlyJJS/lab10VGAdemoJJS/lab10VGAdemoJJS.srcs/constrs_1/new/lab9VGA_wrapper.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top lab9VGA_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef lab9VGA_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file lab9VGA_wrapper_utilization_synth.rpt -pb lab9VGA_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
